### PR TITLE
WebGPU: Added support for formats without storage flag in mip generat…

### LINKED ISSUE #590: WebGPU: support mip generations for formats that do not allow storage access
Formats like 16-bit floats do not allow storage access and as a result, mip generation fails.

### PR DESCRIPTION
**Pull request by MikhailGorobets**
…or (close #590)

### CODE REVIEW

**Comment by MikhailGorobets** [comment]
Can't reproduce issue on WSL

File: Graphics/GraphicsEngineWebGPU/include/TextureViewWebGPUImpl.hpp [hunk 1]
```diff
@@ -61,6 +61,10 @@ class TextureViewWebGPUImpl final : public TextureViewBase<EngineWebGPUImplTrait
 
     WGPUTextureView GetMipLevelSRV(Uint32 Mip);
 
+    WGPUTextureView GetMipLevelRTV(Uint32 Slice, Uint32 Mip);
+
+    WGPUTextureView GetMipLevelSRV(Uint32 Slice, Uint32 Mip);
+
 private:
     WebGPUTextureViewWrapper              m_wgpuTextureView;
     std::vector<WebGPUTextureViewWrapper> m_wgpuTextureMipSRVs;
```
Comment (TheMostDiligent) [inline Graphics/GraphicsEngineWebGPU/include/TextureViewWebGPUImpl.hpp:70]: These views should be in the Texture object

File: Graphics/GraphicsEngineWebGPU/src/TextureWebGPUImpl.cpp [hunk 2]
```diff
@@ -66,10 +69,22 @@ WGPUTextureDescriptor TextureDescToWGPUTextureDescriptor(const TextureDesc&
...
+    {
+        if (FmtInfo.BindFlags & BIND_UNORDERED_ACCESS)
+            wgpuTextureDesc.usage |= WGPUTextureUsage_StorageBinding;
+        else if (FmtInfo.BindFlags & BIND_RENDER_TARGET)
+            wgpuTextureDesc.usage |= WGPUTextureUsage_RenderAttachment;
+        else
+            LOG_ERROR_AND_THROW("Automatic mipmap generation isn't supported for ", GetTextureFormatAttribs(Desc.Format).Name, " as the format can't be used as render target or storage texture");
+
+        if (!FmtInfo.Filterable)
+            LOG_ERROR_AND_THROW("Automatic mipmap generation isn't supported for ", GetTextureFormatAttribs(Desc.Format).Name, " as the format doesn't support linear filtering");
```
Comment (TheMostDiligent) [inline Graphics/GraphicsEngineWebGPU/src/TextureWebGPUImpl.cpp:86]: You can manually filter 4 values in the shader, this way this limitation can be lifted

**Review by TheMostDiligent — CHANGES_REQUESTED** [review]

File: Graphics/GraphicsEngineWebGPU/include/TextureViewWebGPUImpl.hpp (hunk 1 above)
Comment (MikhailGorobets) [reply Graphics/GraphicsEngineWebGPU/include/TextureViewWebGPUImpl.hpp:70]: I specifically asked about this when we first started working on it, and we decided that the logic would be like in D3D12

File: Graphics/GraphicsEngineWebGPU/src/TextureWebGPUImpl.cpp (hunk 2 above)
Comment (MikhailGorobets) [reply Graphics/GraphicsEngineWebGPU/src/TextureWebGPUImpl.cpp:86]: We have the same logic in the Vulkan backend
https://github.com/DiligentGraphics/DiligentCore/blob/a56f176f6afa1adefa1acc9bd7c0afd8891ae692/Graphics/GraphicsEngineVulkan/src/TextureVkImpl.cpp#L118
I think this is not critical because mip generation will only fail for FP32 formats if the device doesn't support this extension `float32-filterable`

**Review by TheMostDiligent — APPROVED** [review]
